### ISSUE TITLE
Define v1.0beta2 features (Biro)

### ISSUE THREAD

**Issue by diegoferigo** [robotology/gym-ignition#87]
~**EDIT**: A more detailed task breakdown in [Milestone v1.0](https://github.com/robotology/gym-ignition/milestone/1).~

---

Gym-Ignition will be presented at SII2020. ~I want to have here a sort of list of features we'd like to have in the first stable release `v1.0`, which will be released before the conference.~ We can use this issue for proposals and discussion.

**Edit:** We've delayed the first stable release due to a big C++ refactoring that is tracked in #155. We presented the first beta version (codename _Aloha_) at SII2020. I converted this issue to contain the features of the second beta release (codename _Biro_).

- [x] C++ and Python feature parity of Robot interfaces (#65)
- [ ] ~Finalize the `RealTimeRuntime`~ (#94)
- [x] Insert a model in Gazebo with fixed pose (#80)
- [ ] ~Implement generic whole-body controllers~ (#88)
- [ ] ~Implement a new task for controlling fixed and floating base robots (test bench for low-level and high-level controllers)~ (#89)
- [x] Simulating with Ignition Gazebo complex robots with many DoFs and meshes (as iCub) (#90)
- [x] Fix meshes rendering (#31)
- [ ] ~Structure better the kwargs of Runtime objects~ (#49)

cc @traversaro @raffaello-camoriano @anqingd @eleramp @CarlottaSartore

**Comment by diegoferigo** [comment]
**Gym-Ignition v1.0beta2 Biro** [has been released](https://github.com/robotology/gym-ignition/releases/tag/v1.0beta2). Closing.
